/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/views/About.vue')['default']
    Count: typeof import('./src/components/Count.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Home: typeof import('./src/views/Home.vue')['default']
    LoveTalk: typeof import('./src/components/LoveTalk.vue')['default']
    News: typeof import('./src/views/News.vue')['default']
    Person: typeof import('./src/views/Person.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
